### ISSUE TITLE
is env is rw

### ISSUE THREAD

**Issue by FCO** [Scimon/p6-Trait-Env#2]
Does it write on the env bar if I do something like thins?

```perl6
class :: { has $.bla is env is rw }.new.bla = “something”;
```

**Comment by Scimon** [comment]
I have not tested 'is rw' it should make the attribute writeable but not effect '%*ENV'. That is how I would like it to work. Clobbering %*ENV feels wrong.
I will test later.

**Comment by Scimon** [comment]
Just done some checking writing to a `is rw` attribute doesn't effect the underlying %*ENV variable. Which I think is the best bet. If you want to modify %*ENV you should do it directly.

Going to close this.
